version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_IN_DOCKER}
      - POSTGRES_USER=${DB_USER_IN_DOCKER}
      - POSTGRES_PASSWORD=${DB_PASSWORD_IN_DOCKER}
    ports:
    - "${DB_PORT_IN_DOCKER}"
  web:
    build: .
    command: python manage.py runserver ${RUN_PORT_IN_DOCKER}
    volumes:
      - .:/code
    ports:
      - "${APP_PORT_IN_DOCKER}"
    depends_on:
      - db
